
server:
  port: 8084



spring:
#  redis:
#    host: 127.0.0.1
## Redis服务器连接端口
#    port: 6379
#    timeout: 20000
  datasource:
      url: jdbc:mysql://localhost:3306/cps?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      #    url: jdbc:mysql://39.100.6.47:3306/precipitate?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
      username: root
      password: 123456
      #    username: jiuyao
      #    password: JiuYao123*
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: User

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.jiuyao.User


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true
